#!/bin/sh

uci -q batch <<-EOF >/dev/null
    set system.@system[0].hostname='BITCORD-RTR-02'
    set system.@system[0].pubname='Роутер BITCORD RTR-02'
    set system.@system[0].timezone='MSK-3'
    set system.@system[0].zonename='Europe/Moscow'
    commit system
    set wireless.default_radio0.key='WFCLokm7Ls'
    set wireless.default_radio0.ssid='BITCORD-RTR-02'
    set wireless.default_radio0.encryption='psk2'
    set wireless.radio0.disabled='0'
    commit wireless
    set dhcp.lan.ra_management='1'
    commit dhcp
EOF

uci -q batch <<-EOF
	set network.tsmodem=interface
	set network.tsmodem.username='root'
	set network.tsmodem.proto='3g'
	set network.tsmodem.device='/dev/ttyUSB2'
	set network.tsmodem.service='umts'
	set network.tsmodem.ipv6='auto'
	set network.tsmodem.apn='internet.mts.ru'
	set network.lan.ifname='3g-tsmodem eth0.1'
	commit network
EOF

uci -q batch <<-EOF
	set firewall.@defaults[0]=defaults
	set firewall.@defaults[0].input='ACCEPT'
	set firewall.@defaults[0].output='ACCEPT'
	set firewall.@defaults[0].forward='ACCEPT'
	set firewall.@defaults[0].synflood_protect='1'
	set firewall.@zone[0]=zone
	set firewall.@zone[0].name='lan'
	set firewall.@zone[0].input='ACCEPT'
	set firewall.@zone[0].output='ACCEPT'
	set firewall.@zone[0].forward='ACCEPT'
	set firewall.@zone[0].network='lan' 'tsmodem'
	set firewall.@zone[1]=zone
	set firewall.@zone[1].name='wan'
	set firewall.@zone[1].output='ACCEPT'
	set firewall.@zone[1].masq='1'
	set firewall.@zone[1].mtu_fix='1'
	set firewall.@zone[1].input='ACCEPT'
	set firewall.@zone[1].forward='ACCEPT'
	set firewall.@zone[1].network='lan' 'tsmodem'
	set firewall.@forwarding[0]=forwarding
	set firewall.@forwarding[0].src='lan'
	set firewall.@forwarding[0].dest='wan'
	set firewall.@forwarding[1]=forwarding
	set firewall.@forwarding[1].dest='lan'
	set firewall.@forwarding[1].src='wan'
	commit firewall
EOF

VDATE=$(opkg info tsmodem | grep Version | awk '{
    print substr($0,10,10)
}')

VNUM=$(opkg info tsmodem | grep Version | awk '{
    print substr($0,30,10)
}')

uci set tsmodem.version.number=$VNUM
uci set tsmodem.version.date=$VDATE
uci commit tsmodem

exit 0
