#!/bin/sh

uci -q batch <<-EOF
    set network.loopback=interface
    set network.loopback.ifname='lo'
    set network.loopback.proto='static'
    set network.loopback.ipaddr='127.0.0.1'
    set network.loopback.netmask='255.0.0.0'
    set network.globals=globals
    set network.globals.ula_prefix='fd65:1e12:de67::/48'
    set network.lan=interface
    set network.lan.type='bridge'
    set network.lan.proto='static'
    set network.lan.ipaddr='192.168.1.1'
    set network.lan.netmask='255.255.255.0'
    set network.lan.ip6assign='60'
    set network.lan_eth0_1_dev=device
    set network.lan_eth0_1_dev.name='eth0.1'
    set network.lan_eth0_1_dev.macaddr='30:eb:1f:14:fa:98'
    set network.wan=interface
    set network.wan.ifname='eth0.2'
    set network.wan.proto='dhcp'
    set network.wan.type='bridge'
    set network.wan_eth0_2_dev=device
    set network.wan_eth0_2_dev.name='eth0.2'
    set network.wan_eth0_2_dev.macaddr='30:eb:1f:14:fa:97'
    set network.wan6=interface
    set network.wan6.ifname='eth0.2'
    set network.wan6.proto='dhcpv6'
    set network.wan6.type='bridge'
    set network.@switch[0]=switch
    set network.@switch[0].name='switch0'
    set network.@switch[0].reset='1'
    set network.@switch[0].enable_vlan='1'
    set network.@switch_vlan[0]=switch_vlan
    set network.@switch_vlan[0].device='switch0'
    set network.@switch_vlan[0].vlan='1'
    set network.@switch_vlan[0].ports='1 2 3 4 6t'
    set network.@switch_vlan[1]=switch_vlan
    set network.@switch_vlan[1].device='switch0'
    set network.@switch_vlan[1].vlan='2'
    set network.@switch_vlan[1].ports='0 6t'
	commit network
EOF

uci -q batch <<-EOF >/dev/null
    set system.@system[0].hostname='BITCORD-RTR-02'
    set system.@system[0].pubname='Роутер BITCORD RTR-02'
    set system.@system[0].timezone='MSK-3'
    set system.@system[0].zonename='Europe/Moscow'
    commit system
    set network.lan.ifname='eth0.1'
    set network.lan.dns='8.8.8.8'
    set network.wwan=interface
    set network.wwan.proto='dhcp'
    set network.tsmodem.ipv6='auto'
    set network.tsmodem=interface
    set network.tsmodem.username='root'
    set network.tsmodem.proto='3g'
    set network.tsmodem.device='/dev/ttyUSB2'
    set network.tsmodem.dialnumber='*99***1#'
    set network.tsmodem.service='umts'
    set network.tsmodem.pppd_options='debug noipdefault'
    set network.tsmodem.keepalive='500 5'
    set network.tsmodem.apn='internet
    commit network
    set wireless.default_radio0.network='wwan lan wan wan6'
    set wireless.default_radio0.key='WFCLokm7Ls'
    set wireless.default_radio0.ssid='BITCORD-RTR-02'
    set wireless.default_radio0.encryption='psk2'
    commit wireless
    set firewall.@zone[0].network='lan'
    set firewall.@zone[1].network='wan wan6 3g tsmodem wwan tsmodem'
    commit firewall
    set luci.main.lang='ru'
    set luci.ccache.enable='0'
    commit luci
EOF

VDATE=$(opkg info tsmodem | grep Version | awk '{
    print substr($0,10,10)
}')

VNUM=$(opkg info tsmodem | grep Version | awk '{
    print substr($0,30,10)
}')

uci set tsmodem.version.number=$VNUM
uci set tsmodem.version.date=$VDATE
uci commit tsmodem

exit 0
