#!/bin/sh

uci -q batch <<-EOF >/dev/null
    set system.@system[0].hostname='BITCORD-RTR-02'
    set system.@system[0].pubname='Роутер BITCORD RTR-02'
    set system.@system[0].timezone='MSK-3'
    set system.@system[0].zonename='Europe/Moscow'
    commit system
    set wireless.default_radio0.key='bitcord999'
    set wireless.default_radio0.ssid='BITCORD-RTR-02'
    set wireless.default_radio0.encryption='psk2'
    set wireless.radio0.disabled='0'
    commit wireless
EOF

uci -q batch <<-EOF
	set network.tsmodem=interface
	set network.tsmodem.username='root'
	set network.tsmodem.proto='3g'
	set network.tsmodem.device='/dev/ttyUSB2'
	set network.tsmodem.service='umts'
	set network.tsmodem.ipv6='auto'
	set network.tsmodem.apn='internet.mts.ru'
	commit network
EOF

uci -q batch <<-EOF
	add_list firewall.@zone[1].network='tsmodem'
	commit firewall
EOF

exit 0
