#
# Copyright (C) 2008-2019 Jerrykuku
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=TSmodem Theme
PKG_NAME:=luci-theme-tsmodem
PKG_VERSION:=2.2.0
PKG_RELEASE:=20221120

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
