#!/bin/sh

uci -q batch <<-EOF >/dev/null
    set system.@system[0].hostname='BITCORD-RTR-2'
    set system.@system[0].pubname='Роутер BITCORD RTR-2'
    set system.@system[0].timezone='MSK-3'
    set system.@system[0].zonename='Europe/Moscow'
    commit system
EOF

uci -q batch <<-EOF >/dev/null
    set network.@device[0]=device
    set network.@device[0].name='br-lan'
    set network.@device[0].type='bridge'
    set network.@device[0].ports='eth0.1'
    set network.lan=interface
    set network.lan.device='br-lan'
    set network.lan.proto='static'
    set network.lan.ipaddr='192.168.1.1'
    set network.lan.netmask='255.255.255.0'
    set network.lan.dns='8.8.8.8'
    set network.lan.ip6assign='60'
    set network.@device[1]=device
    set network.@device[1].name='eth0.2'
    set network.@device[1].macaddr='30:eb:1f:3d:e9:2f'
    commit network
EOF

uci -q batch <<-EOF >/dev/null
    set network.modem=interface
    set network.modem.username='root'
    set network.modem.proto='3g'
    set network.modem.device='/dev/ttyUSB2'
    set network.modem.dialnumber='*99***1#'
    set network.modem.service='umts'
    set network.modem.pppd_options='noipdefault'
    set network.modem.ipv6='auto'
    set network.modem.apn='internet.megafon.ru'
    commit network 
EOF

uci -q batch <<-EOF >/dev/null
    set network.wifi=interface
    set network.wifi.proto='static'
    set network.wifi.device='phy0-ap0'
    set network.wifi.ipaddr='192.168.2.1'
    set network.wifi.netmask='255.255.255.0'
    set network.wifi.ip4table='default'
    set network.wifi.ip6table='default'
    commit network
EOF

uci -q batch <<-EOF >/dev/null
    add dhcp modem
    set dhcp.modem.interface='modem'
    set dhcp.modem.start='100'
    set dhcp.modem.limit='150'
    set dhcp.modem.leasetime='12h'
    commit dhcp
EOF

uci -q batch <<-EOF >/dev/null
    set firewall.@defaults[0]=defaults
    set firewall.@defaults[0].input='ACCEPT'
    set firewall.@defaults[0].output='ACCEPT'
    set firewall.@defaults[0].forward='ACCEPT'
    set firewall.@defaults[0].synflood_protect='0'
    set firewall.@zone[0]=zone
    set firewall.@zone[0].name='lan'
    set firewall.@zone[0].input='ACCEPT'
    set firewall.@zone[0].output='ACCEPT'
    set firewall.@zone[0].forward='ACCEPT'
    set firewall.@zone[0].masq='1'
    set firewall.@zone[0].network='lan'
    commit firewall
    add firewall zone
    set firewall.@zone[-1].name='3g'
    set firewall.@zone[-1].input='ACCEPT'
    set firewall.@zone[-1].output='ACCEPT'
    set firewall.@zone[-1].forward='ACCEPT'
    set firewall.@zone[-1].masq='1'
    add_list firewall.@zone[-1].device='3g-modem'
    add_list firewall.@zone[-1].network='modem'
    add firewall forwarding
    set firewall.@forwarding[-1].src='3g'
    set firewall.@forwarding[-1].dest='lan'
    add firewall forwarding
    set firewall.@forwarding[-1].src='lan'
    set firewall.@forwarding[-1].dest='3g'
    commit firewall
EOF

uci -q batch <<-EOF >/dev/null
    set wireless.radio0=wifi-device
    set wireless.radio0.type='mac80211'
    set wireless.radio0.hwmode='11g'
    set wireless.radio0.path='platform/10300000.wmac'
    set wireless.radio0.htmode='HT20'
    set wireless.radio0.disabled='1'
    set wireless.radio0.channel='1'
    set wireless.radio0.band='2g'
    set wireless.radio0.cell_density='1'
    set wireless.default_radio0=wifi-iface
    set wireless.default_radio0.device='radio0'
    set wireless.default_radio0.mode='ap'
    set wireless.default_radio0.network='wwan wifi'
    set wireless.default_radio0.ssid='BITCORD-RTR-2'
    set wireless.default_radio0.encryption='psk2'
    set wireless.default_radio0.key='WFCLokm7Ls'
    commit wireless
EOF

uci -q batch <<-EOF >/dev/null
    set luci.main.lang='ru'
    set luci.main.mediaurlbase='/luci-static/tsmodem'
    set luci.languages=internal
    set luci.languages.ru='Русский (Russian)'
    set luci.ccache=internal
    set luci.ccache.enable='0'
    set luci.themes=internal
    set luci.themes.Bootstrap='/luci-static/bootstrap'
    set luci.themes.tsmodem='/luci-static/tsmodem'
    commit luci
EOF

VDATE=$(opkg info tsmodem | grep Version | awk '{
    print substr($0,10,10)
}')

VNUM=$(opkg info tsmodem | grep Version | awk '{
    print substr($0,30,10)
}')

uci set tsmodem.version.number=$VNUM
uci set tsmodem.version.date=$VDATE
uci commit tsmodem

exit 0
