#!/bin/sh

uci -q batch <<-EOF >/dev/null
    add firewall zone
    set firewall.@zone[-1].name='vpn'
    set firewall.@zone[-1].input='ACCEPT'
    set firewall.@zone[-1].output='ACCEPT'
    set firewall.@zone[-1].forward='ACCEPT'
    set firewall.@zone[-1].masq='1'
    set firewall.@zone[-1].mtu_fix='1'
    add firewall forwarding
    set firewall.@forwarding[-1].src='lan'
    set firewall.@forwarding[-1].dest='vpn'
    add firewall forwarding
    set firewall.@forwarding[-1].src='vpn'
    set firewall.@forwarding[-1].dest='lan'
    commit firewall
EOF

exit 0


