#!/bin/sh

uci -q batch <<-EOF >/dev/null
    set network.vpnpptp=interface
    set network.vpnpptp.proto='pptp'
    set network.vpnpptp.username='gan-vpnjantit.com'
    set network.vpnpptp.ipv6='auto'
    set network.vpnpptp.password='gJ915009'
    set network.vpnpptp.server='se1.vpnjantit.com'
    set network.vpnpptp.auto='0'
    commit network
EOF

exit 0