#!/bin/sh

uci -q batch <<-EOF >/dev/null
    set network.vpnpptp=interface
    set network.vpnpptp.proto='pptp'
    set network.vpnpptp.username='gan-vpnjantit.com'
    set network.vpnpptp.ipv6='auto'
    set network.vpnpptp.password='gJ915009'
    set network.vpnpptp.server='se1.vpnjantit.com'
    set network.vpnpptp.auto='0'
    commit network
EOF

# add 'vpnpptp' to covered network for 'vpn' zone of the Firewall; something like this:
# firewall.@zone[3].network='openvpn' 'vpnpptp'

ZONEID=$(uci show firewall | grep "name='vpn'" | awk -F "." '{print $2}')

[[ -n $ZONEID ]] && {
    ZONES=$(uci get firewall.$ZONEID.network)

    uci del firewall.$ZONEID.network

    for i in $(echo $ZONES | tr " " "\n")
    do
        uci add_list firewall.$ZONEID.network=$i
    done

    uci add_list firewall.$ZONEID.network='vpnpptp'
    uci commit firewall
}


exit 0