#!/bin/sh

[ "$INTERFACE" = openvpn ] && [ "$ACTION" = ifup ] && {
	TUNIP=$(/sbin/ip addr show tun0 | grep peer | awk ' { print $4 } ' | sed 's/\/32//')
	ip route add 192.168.1.0/24 via 192.168.1.1 dev br-lan
	ip route add 0.0.0.0/1 via $TUNIP dev tun0
}

[ "$INTERFACE" = openvpn ] && [ "$ACTION" = ifdown ] && {
	TUNIP=$(/sbin/ip addr show tun0 | grep peer | awk ' { print $4 } ' | sed 's/\/32//')
	ip route del 192.168.1.0/24 via 192.168.1.1 dev br-lan
	ip route del 0.0.0.0/1 via $TUNIP dev tun0
}

